### ISSUE TITLE
I can't stop spinning until Julia exits

### ISSUE THREAD

**Issue by ararslan** [KristofferC/TerminalSpinners.jl#1]
I just did
```julia
s = Spinner()
autospin(s)
```
at the REPL and felt existentially fulfilled, but then I tried to stop it and I couldn't; ^C didn't work, only ^D'ing into oblivion.

**Comment by KristofferC** [comment]
Lol, it starts a new thread with the spinner. You need to `stop!` it. But this is really not ready for use yet heh.
